const APP_META={direct:{label:'가게바로주문',icon:'🏪'},mukkebi:{label:'먹깨비',icon:'assets/mukkebi-v7.png'},ddangyo:{label:'땡겨요',icon:'assets/ddangyo-v7.png'},yogiyo:{label:'요기요',icon:'assets/yogiyo.jpg'},coupang:{label:'쿠팡이츠',icon:'assets/coupang-eats.jpg'},baemin:{label:'배달의민족',icon:'assets/baemin.jpg'}};
const $=s=>document.querySelector(s),$$=s=>[...document.querySelectorAll(s)];
const state={query:'',category:'전체',slide:0};
let stores=[];
const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const norm=v=>String(v??'').trim().toLowerCase().replace(/\s+/g,'');
function routeKey(name=''){const n=norm(name);if(n.includes('가게바로')||n.includes('직접주문'))return'direct';if(n.includes('먹깨비'))return'mukkebi';if(n.includes('땡겨요'))return'ddangyo';if(n.includes('요기요'))return'yogiyo';if(n.includes('쿠팡'))return'coupang';if(n.includes('배달의민족')||n.includes('배민'))return'baemin';return'';}
function adapt(raw,i){const links={};(raw.routes||[]).forEach(r=>{if(r&&r.enabled!==false&&r.url){const k=routeKey(r.name);if(k&&!links[k])links[k]=r.url;}});const tags=[...(raw.searchTerms||[]),...(raw.categories||[]),...(raw.areas||[]),...(raw.shopInShopNames||[]),raw.realBusinessName,raw.category,raw.district,raw.address].filter(Boolean);return{...raw,id:raw.id||`store-${i}`,name:raw.name||raw.realBusinessName||`가게 ${i+1}`,area:raw.district||raw.area||'여수',cat:raw.category||raw.cat||'음식점',phone:raw.phone||'',img:raw.image||raw.img||'assets/store1.jpg',tags,links};}
async function loadStores(){const res=await fetch(`data/stores.json?v=${Date.now()}`,{cache:'no-store'});if(!res.ok)throw new Error(`stores.json ${res.status}`);const raw=await res.json();if(!Array.isArray(raw))throw new Error('stores.json 형식 오류');stores=raw.map(adapt);console.info(`가게 DB ${stores.length}개 로드 완료`);}
const categories=[['🍲','한식'],['🍗','치킨'],['🍕','피자'],['🍜','중식'],['🍢','분식'],['🥩','족발·보쌈'],['🐟','회·해산물']];
const allCategories=[...categories,['🍔','햄버거'],['🥘','고기·구이'],['🌙','야식·주점'],['🌶️','마라탕·양꼬치'],['🥗','반찬'],['☕','카페·디저트']];
const areas=['여수시 전체','공화동','관문동','고소동','교동','광무동','국동','남산동','덕충동','동문동','둔덕동','만흥동','미평동','문수동','봉강동','봉산동','서교동','소라면','소호동','시전동','신기동','안산동','여서동','연등동','오림동','웅천동','월호동','율촌면','종화동','중앙동','충무동','학동','화장동','화정면','돌산읍','삼일동','묘도동','주삼동'];
const ads=[{title:'신규 오픈 가게를 만나보세요',desc:'여수의 새로운 맛집과 특별한 혜택',bg:'assets/store4.jpg'},{title:'배송기사님 모집',desc:'베테랑 배달연합과 함께할 기사님을 찾습니다',bg:'assets/store2.jpg'},{title:'배달대행 가맹점 모집',desc:'가게 사장님을 위한 주문·홍보·배달 연결',bg:'assets/store1.jpg'},{title:'먹깨비·땡겨요·온동네 가입 안내',desc:'저수수료 주문경로를 손쉽게 연결하세요',bg:'assets/store3.jpg'},{title:'소상공인협회 알림',desc:'여수 소상공인을 위한 중요한 소식',bg:'assets/store2.jpg'}];
function appIcon(k,cls=''){const m=APP_META[k];if(!m)return'';return m.icon.startsWith('assets/')?`<img class="${cls}" src="${m.icon}" alt="${m.label}">`:`<span class="${cls} emoji-app">${m.icon}</span>`;}
function relevance(s,q){q=norm(q);if(!q)return 0;const name=norm(s.name),tags=s.tags.map(norm);if(name===q)return 100;if(name.startsWith(q))return 90;if(name.includes(q))return 80;if(tags.includes(q))return 70;if(tags.some(t=>t.includes(q)||q.includes(t)))return 60;if(norm(s.cat).includes(q)||norm(s.area).includes(q))return 50;return norm([s.name,s.area,s.cat,...s.tags].join(' ')).includes(q)?40:0;}
function searchList(q){const direct=stores.map(s=>({s,score:relevance(s,q)})).filter(x=>x.score>0).sort((a,b)=>b.score-a.score).map(x=>x.s);if(!direct.length)return[];const cats=new Set(direct.slice(0,10).map(s=>s.cat));return[...direct,...stores.filter(s=>!direct.some(d=>d.id===s.id)&&cats.has(s.cat))];}
function recommend(){return stores.filter(s=>state.category==='전체'||s.cat===state.category).slice(0,40);}
function storeCard(s){const keys=['mukkebi','ddangyo','yogiyo','coupang','baemin'].filter(k=>s.links[k]);return`<article class="store-card" data-id="${esc(s.id)}"><img src="${esc(s.img)}" alt="${esc(s.name)}" onerror="this.src='assets/store1.jpg'"><div class="store-info"><h3>${esc(s.name)}</h3><p>${esc(s.area)} · ${esc(s.cat)}</p><div class="miniapps">${keys.map(k=>appIcon(k,'miniapp-icon')).join('')}</div></div><button class="order-open">주문방법 보기</button></article>`;}
function renderStores({scroll=false}={}){const q=state.query.trim();let list,title;if(q){const found=searchList(q);$('#searchSummary').hidden=false;if(found.length){list=found;title=`'${esc(q)}' 검색 결과`;$('#searchSummary').innerHTML=`<strong>검색 결과 ${found.length}곳</strong><button id="clearSearch" class="text-btn">검색 초기화</button>`;}else{list=recommend();title='검색 결과가 없어 추천 가게를 보여드립니다';$('#searchSummary').innerHTML=`<strong>'${esc(q)}' 검색 결과가 없습니다.</strong><button id="clearSearch" class="text-btn">검색 초기화</button>`;}}else{list=recommend();title=state.category==='전체'?'오늘의 추천':`${state.category} 추천`;$('#searchSummary').hidden=true;}$('#recommendSection h2').textContent=title;$('#resetCategoryBtn').hidden=state.category==='전체';$('#storeGrid').innerHTML=list.length?list.map(storeCard).join(''):'<div class="empty">등록된 가게가 없습니다.</div>';if(scroll)$('#recommendSection').scrollIntoView({behavior:'smooth',block:'start'});}
function renderAds(){$('#heroTrack').innerHTML=ads.map(a=>`<article class="hero-card" style="background-image:url('${a.bg}')"><h2>${a.title}</h2><p>${a.desc}</p></article>`).join('');$('#heroDots').innerHTML=ads.map((_,i)=>`<i class="${i?'':'active'}"></i>`).join('');}
function showSlide(i){state.slide=(i+ads.length)%ads.length;$('#heroTrack').style.transform=`translateX(-${state.slide*100}%)`;$$('#heroDots i').forEach((d,j)=>d.classList.toggle('active',j===state.slide));}
function openModal(html){$('#modalContent').innerHTML=html;$('#overlay').hidden=false;$('#modal').hidden=false;document.body.style.overflow='hidden';history.pushState({modal:true},'');}
function closeModal(fromPop=false){if($('#modal').hidden)return;$('#modal').hidden=true;$('#overlay').hidden=true;document.body.style.overflow='';if(!fromPop&&history.state?.modal)history.back();}
function detail(s){const primary=['direct','mukkebi','ddangyo'].filter(k=>s.links[k]).map(k=>`<a class="detail-route" href="${esc(s.links[k])}" ${String(s.links[k]).startsWith('http')?'target="_blank" rel="noopener"':''}>${appIcon(k,'detail-route-icon')}<span>${APP_META[k].label}</span><b>›</b></a>`).join('');const others=['yogiyo','coupang','baemin'].filter(k=>s.links[k]);const other=others.length?`<div class="store-other-wrap"><button class="detail-route store-other-toggle"><span>다른 주문앱 보기</span><span class="other-inline-icons">${others.map(k=>appIcon(k,'other-inline-icon')).join('')}</span><b>›</b></button><div class="store-other-popover" hidden><button class="store-other-close" aria-label="닫기">×</button>${others.map(k=>`<a href="${esc(s.links[k])}" target="_blank" rel="noopener">${appIcon(k,'store-other-icon')}<span>${APP_META[k].label}</span></a>`).join('')}</div></div>`:'';const phone=s.phone?`<a class="detail-route" href="tel:${esc(s.phone)}"><span class="detail-route-icon emoji-app">☎</span><span>전화주문 ${esc(s.phone)}</span><b>›</b></a>`:'';openModal(`<h2>${esc(s.name)}</h2><img src="${esc(s.img)}" class="detail-photo" alt="${esc(s.name)}" onerror="this.src='assets/store1.jpg'"><p>${esc(s.area)} · ${esc(s.cat)}</p><div class="detail-routes">${primary}${phone}${other}</div>`);}
function bind(){renderAds();setInterval(()=>showSlide(state.slide+1),3500);$('#categoryGrid').innerHTML=categories.map(([e,n])=>`<button class="category" data-cat="${n}"><span class="bubble">${e}</span><span>${n}</span></button>`).join('');const input=$('#mainSearch'),clear=$('#clearMainSearch');input.oninput=()=>clear.hidden=!input.value;input.onkeydown=e=>{if(e.key==='Enter')$('#searchBtn').click();};clear.onclick=()=>{input.value='';state.query='';clear.hidden=true;renderStores();input.focus();};$('#searchBtn').onclick=()=>{state.query=input.value.trim();state.category='전체';renderStores({scroll:true});};$('#categoryGrid').onclick=e=>{const b=e.target.closest('[data-cat]');if(!b)return;state.category=b.dataset.cat;state.query='';input.value='';clear.hidden=true;renderStores({scroll:true});};$('#resetCategoryBtn').onclick=()=>{state.category='전체';renderStores({scroll:true});};document.addEventListener('click',e=>{if(e.target.id==='clearSearch'){state.query='';input.value='';renderStores();}const card=e.target.closest('.store-card');if(card){const s=stores.find(x=>String(x.id)===card.dataset.id);if(s)detail(s);return;}const toggle=e.target.closest('.store-other-toggle');if(toggle){e.preventDefault();e.stopPropagation();const menu=toggle.parentElement.querySelector('.store-other-popover');menu.hidden=!menu.hidden;return;}if(e.target.closest('.store-other-close')){e.preventDefault();e.target.closest('.store-other-popover').hidden=true;return;}if(!e.target.closest('.store-other-wrap'))$$('.store-other-popover').forEach(x=>x.hidden=true);});$('.modal-close').onclick=()=>closeModal();$('#overlay').onclick=()=>closeModal();const pop=$('#moreAppsPopover');$('#moreAppsBtn').onclick=e=>{e.stopPropagation();pop.hidden=!pop.hidden;};$('.popover-close').onclick=()=>pop.hidden=true;document.addEventListener('click',e=>{if(!pop.hidden&&!e.target.closest('#moreAppsPopover')&&!e.target.closest('#moreAppsBtn'))pop.hidden=true;});$('#locationText').textContent=localStorage.getItem('location')||'여수시 전체';$('#allCategoryBtn').onclick=()=>openModal(`<h2>전체 음식 카테고리</h2><div class="all-category-list">${allCategories.map(([e,n])=>`<button data-modal-cat="${n}"><span>${e}</span><b>${n}</b></button>`).join('')}</div>`);document.addEventListener('click',e=>{const b=e.target.closest('[data-modal-cat]');if(!b)return;state.category=b.dataset.modalCat;state.query='';input.value='';closeModal();setTimeout(()=>renderStores({scroll:true}),50);});$('#noticeBtn').onclick=()=>openModal('<h2>알림</h2><div class="my-list"><button>신규 오픈 가게 안내</button><button>배송기사님 모집 안내</button><button>가맹점 모집 안내</button></div>');}
async function bootstrap(){try{await loadStores();bind();renderStores();}catch(err){console.error(err);$('#searchSummary').hidden=false;$('#searchSummary').innerHTML=`<strong>가게 데이터를 불러오지 못했습니다.</strong><span>${esc(err.message)}</span>`;$('#storeGrid').innerHTML='<div class="empty">data/stores.json과 Live Server를 확인해 주세요.</div>';}}
bootstrap();