import fs from 'node:fs';

const stores=JSON.parse(fs.readFileSync('data/stores.json','utf8'));
const manifest=JSON.parse(fs.readFileSync('data/photo-manifest.json','utf8'));
const policy=JSON.parse(fs.readFileSync('data/photo-policy.json','utf8'));
const assignments=JSON.parse(fs.readFileSync('data/photo-batch2-vetted-assignments.json','utf8'));
const assets=JSON.parse(fs.readFileSync('data/photo-batch2-vetted-assets.json','utf8'));
const checks=[];const warnings=[];const errors=[];
const check=(condition,message)=>condition?checks.push(message):errors.push(message);
const warn=(condition,message)=>{if(condition)warnings.push(message);};
const normalize=value=>String(value??'').trim().toLowerCase().replace(/[\s·&()\-_/.,]/g,'');
const hasPhoto=store=>Boolean(String(store.image||store.img||'').trim()||(Array.isArray(store.images)&&store.images.length));

check(stores.length===471,`가게 수 471개: ${stores.length}`);
check(new Set(stores.map(store=>String(store.id))).size===471,'가게 ID 중복 없음');
check(new Set(stores.map(store=>normalize(store.name))).size===471,'정규화 가게명 중복 없음');
check(stores.every(store=>String(store.name||'').trim()),'가게명 누락 없음');
const management=stores.filter(store=>/^대동여수음식지도(?:\s|\(|$)/.test(String(store.name||'').trim()));
check(management.length===0,'관리용 노션 페이지 제외');
const withPhoto=stores.filter(hasPhoto).length;
check(withPhoto===386,`사진 보유 386곳: ${withPhoto}`);
check(stores.length-withPhoto===85,`사진 준비 중 85곳: ${stores.length-withPhoto}`);
check(manifest.coverage?.storesWithPhoto===386&&manifest.coverage?.storesAwaitingPhoto===85,'사진 매니페스트 386/85 일치');
const package1=(manifest.packages||[]).find(item=>item.id==='photo-batch-1-final');
check(package1?.runtimeEnabled===false&&package1?.status==='incomplete','1차 패키지 비활성 유지');
check(JSON.stringify(package1?.missingPartNumbers)==='[18,19,20,21,22]','1차 누락 18~22 기록 유지');
const package2=(manifest.packages||[]).find(item=>item.id==='photo-batch-2');
check(package2?.runtimeEnabled===true&&package2?.status==='active-revalidated','2차 패키지 검증 활성 유지');
check(package2?.revalidatedApprovedImages===9&&package2?.appliedStores===14,'2차 사진 9장·가게 14곳 유지');
check(assets.assets?.length===9,'2차 WebP 자산 9장');
check(assignments.assignments?.length===14,'2차 적용 가게 목록 14곳');
const referenced=new Set(assignments.assignments.flatMap(item=>item.paths||[]));
check(referenced.size===9,'2차 실제 참조 파일 9장');
const categories=[...new Set(stores.map(store=>store.category||store.cat).filter(Boolean))];
check(categories.length>=12,`전체 음식 카테고리 제공: ${categories.length}개`);
const invalidRoutes=[];
for(const store of stores)for(const route of store.routes||[])if(route.enabled!==false&&!/^(https?:\/\/|tel:)/i.test(String(route.url||'')))invalidRoutes.push([store.name,route.name,route.url]);
check(invalidRoutes.length===0,'주문경로 URL 형식 정상');
const blocked=(policy.blockedPathKeywords||[]).map(normalize);
const suspicious=stores.filter(store=>blocked.some(keyword=>normalize([store.image,store.img,store.name,store.realBusinessName].join(' ')).includes(keyword)));
check(suspicious.length===0,'민감서류·가격표·영수증 경로 차단');
for(const classification of ['sensitive_document','price_list','receipt','personal_information','identity_document','contract','non_food'])check((policy.blockedClassifications||[]).includes(classification),`차단 분류 존재: ${classification}`);
warn(stores.length-withPhoto===85,'사진 없는 85곳은 검수된 음식 사진 준비 중으로 유지');
warn(package1?.runtimeEnabled===false,'1차 스프라이트는 전체 기능 통합을 막지 않고 비활성 유지');

console.log('\n[데이터검사 결과]');
for(const item of checks)console.log('PASS ',item);
for(const item of warnings)console.log('WARN ',item);
for(const item of errors)console.log('FAIL ',item);
const report={success:errors.length===0,pass:checks.length,warn:warnings.length,fail:errors.length,photoCoverage:{withPhoto,awaiting:stores.length-withPhoto},categories:categories.length,checks,warnings,errors};
fs.writeFileSync('data-validation-report.json',JSON.stringify(report,null,2)+'\n');
console.log(`\nPASS ${report.pass} / WARN ${report.warn} / FAIL ${report.fail}`);
if(errors.length)process.exit(1);
